using System;

namespace Legacy.Core.PartyManagement
{
	public enum EPartyBuffs
	{
		NONE,
		FIRE_WARD,
		WATER_WARD,
		AIR_WARD,
		EARTH_WARD,
		LIGHT_WARD,
		DARKNESS_WARD,
		ARCANE_WARD,
		TORCHLIGHT,
		LIGHT_ORB,
		DARK_VISION,
		INNER_FIRE,
		HEROIC_DESTINY,
		EAGLE_EYE,
		FIRE_SHIELD,
		WIND_SHIELD,
		REGENERATION,
		STONE_SKIN,
		SHADOW_CLOAK,
		CELESTIAL_ARMOR,
		HOUR_OF_POWER,
		WELL_RESTED,
		DANGER_SENSE,
		CLAIRVOYANCE,
		WHISPERING_SHADOWS,
		BURNING_DETERMINATION,
		LIQUID_MEMBRANE,
		FIRE_WARD_CRYSTAL,
		WATER_WARD_CRYSTAL,
		AIR_WARD_CRYSTAL,
		EARTH_WARD_CRYSTAL,
		LIGHT_WARD_CRYSTAL,
		DARKNESS_WARD_CRYSTAL,
		ARCANE_WARD_CRYSTAL,
		HEROIC_DESTINY_STATUE,
		HOUR_OF_POWER_STATUE,
		MANDATE_OF_HEAVEN,
		NURTURE
	}
}
