using System;

namespace Legacy.Core.PartyManagement
{
	public enum ETokenID
	{
		TOKEN_BLESSING_SPOT_SECRETS = 1,
		TOKEN_BLESSING_CLAIRVOYANCE,
		TOKEN_BLESSING_DANGER_SENSE,
		TOKEN_BLESSING_ENTER_WATER,
		TOKEN_BLESSING_ENTER_ROUGH,
		TOKEN_BLESSING_ENTER_FOREST,
		TOKEN_STORY_ACT_1,
		TOKEN_STORY_ACT_2,
		TOKEN_STORY_ACT_3,
		TOKEN_STORY_ACT_4,
		TOKEN_CLASS_WINDSWORD,
		TOKEN_CLASS_PALADIN,
		TOKEN_CLASS_ARCHMAGE,
		TOKEN_CLASS_BLADEMASTER,
		TOKEN_CLASS_WARDEN,
		TOKEN_CLASS_DRUID_ELDER,
		TOKEN_CLASS_SHIELD_GUARD,
		TOKEN_CLASS_PATHFINDER,
		TOKEN_CLASS_RUNELORD,
		TOKEN_CLASS_WARMONGER,
		TOKEN_CLASS_MARAUDER,
		TOKEN_CLASS_BLOODCALLER,
		TOKEN_KILLED_IVEN = 544,
		TOKEN_FOUND_HAMATO,
		TOKEN_KILLED_EREBOS = 699,
		TOKEN_RACE_IN_PARTY_HUMAN = 736,
		TOKEN_RACE_IN_PARTY_ORC,
		TOKEN_RACE_IN_PARTY_ELF,
		TOKEN_RACE_IN_PARTY_DWARF,
		TOKEN_RANGER_IN_PARTY = 757,
		TOKEN_DLC_FINISHED = 800
	}
}
