using System;

namespace Legacy.Core.Entities.Skills
{
	public enum ESkillEffectType
	{
		NONE,
		INCREASE_ATTACK_VALUE,
		INCREASE_DAMAGE_FACTOR,
		INCREASE_DAMAGE_SKILL_BONUS,
		INCREASE_MAGIC_FACTOR_SKILL_BONUS,
		ADDITIONAL_STRIKE,
		INCREASE_CRITICAL_HIT_CHANCE,
		INCREASE_CRITICAL_DAMAGE,
		INCREASE_CRITICAL_MAGIC_DAMAGE,
		INCREASE_CRITICAL_MAGIC_HIT_CHANCE,
		STUN_MONSTER,
		ADDITIONAL_MAIN_HAND_STRIKE,
		ADDITIONAL_BLOCK_ATTEMPT,
		ADDITIONAL_MELEE_BLOCK_ATTEMPT,
		IGNORE_ARMOR_VALUE,
		INCREASE_CRITICAL_HIT_DESTINY_MULTIPLIER,
		DECREASE_DAMAGE_PENALTY,
		DECREASE_ATTACK_VALUE_PENALTY,
		IGNORE_BLOCKS,
		SET_ATTACK_RANGE,
		PIERCE_ATTACK,
		INCREASE_BLOCK_CHANCE,
		COUNTER_ATTACK,
		BLOCK_PARTY_CHARACTER_ATTACK,
		LEARN_SPELL,
		INCREASE_MAXIMUM_HEALTH,
		INCREASE_MAXIMUM_MANA,
		INCREASE_MAGIC_RESISTANCE,
		REDUCE_INCOMING_CRITICAL_DAMAGE,
		RESTORE_MANA,
		INCREASE_EVADE_VALUE,
		INCREASE_ARMOR_VALUE,
		IGNORE_RESISTANCE,
		APPLY_GASH,
		REDUCE_INCOMING_CRITICAL_MAGIC_DAMAGE,
		RESTORE_MANA_ON_RESIST_MAGIC
	}
}
