using System;

namespace Legacy.Core.Entities.Skills
{
	public enum ESkillID
	{
		SKILL_DAGGER = 1,
		SKILL_BOW,
		SKILL_CROSSBOW,
		SKILL_MACE,
		SKILL_AXE,
		SKILL_SWORD,
		SKILL_SPEAR,
		SKILL_TWOHANDED,
		SKILL_SHIELD,
		SKILL_DUAL_WIELD,
		SKILL_WARFARE,
		SKILL_MEDIUM_ARMOR,
		SKILL_HEAVY_ARMOR,
		SKILL_DODGE,
		SKILL_ENDURANCE,
		SKILL_ARCANE_DISCIPLINE,
		SKILL_MAGICAL_FOCUS,
		SKILL_MYSTICISM,
		SKILL_FIRE_MAGIC,
		SKILL_WATER_MAGIC,
		SKILL_AIR_MAGIC,
		SKILL_EARTH_MAGIC,
		SKILL_LIGHT_MAGIC,
		SKILL_DARK_MAGIC,
		SKILL_PRIMORDIAL_MAGIC
	}
}
