using System;

namespace Legacy.Core
{
	public enum EMonsterAbilityType
	{
		NONE,
		REGENERATION,
		PAIN_REFLECTION,
		EXPLOSIVE,
		RETALIATION,
		ENRAGED,
		VINDICTIVE,
		SWEEPING_ATTACK,
		RELENTLESS,
		STUNNING_STRIKES,
		WEAKENING_STRIKES,
		CURSING_STRIKES,
		CONFUSING_STRIKES,
		POISONING_STRIKES,
		LARGE,
		MANA_LEECH,
		FOCUSED,
		BURNING,
		UNDEAD,
		DEMONIC_LINEAGE,
		VULNERABILITY_LIGHT,
		VULNERABILITY_AIR,
		VULNERABILITY_WATER,
		VULNERABILITY_EARTH,
		VULNERABILITY_FIRE,
		VULNERABILITY_DARKNESS,
		CURLING,
		PUSH,
		BOSS,
		SHADOW_CLOAK,
		VANISH,
		STATIC_OBJECT,
		SPIRIT_BOUND,
		MARTYR,
		PIERCING_STRIKES,
		UNSTOPPABLE_STRIKES,
		SPEED_OF_LIGHT
	}
}
