using System;

namespace Legacy.Core.Entities.InteractiveObjects
{
	public enum EInteractiveObjectData
	{
		PREFAB,
		IS_SECRET,
		STATE,
		INDOOR_SCENE,
		NPC_IDS,
		AUTOSTART_NPC,
		START_DIALOG_ID,
		SHOW_NPCS,
		MINIMAP_TOOLTIP,
		CONTAINER_ITEM,
		CONTAINER_GOLD,
		CONDITIONAL_DATA,
		CUTSCENE_TARGET_SPAWNID,
		TRAP_DATA,
		TRAP_EFFECT_DATA,
		CONTAINER_TOKEN,
		COUNTER_OBJECT_DATA,
		CONTAINER_BOOK,
		CONTAINER_GENERATED,
		BARREL_DATA,
		RECHARGING_OBJECT_DATA,
		CHALLENGE
	}
}
