using System;

namespace Legacy.Core.NpcInteraction
{
	public enum EDialogReplacement
	{
		NONE,
		ALL_CHARS,
		CLASS_MERCENARY,
		CLASS_CRUSADER,
		CLASS_FREEMAGE,
		CLASS_BLADEDANCER,
		CLASS_RANGER,
		CLASS_DRUID,
		CLASS_DEFENDER,
		CLASS_SCOUT,
		CLASS_RUNEPRIEST,
		CLASS_BARBARIAN,
		CLASS_HUNTER,
		CLASS_SHAMAN,
		RACE_HUMAN,
		RACE_DWARF,
		RACE_ELF,
		RACE_ORC,
		FEATURE_PRICE,
		SKILL_EXPERT_PRICE,
		SKILL_MASTER_PRICE,
		SKILL_GRANDMASTER_PRICE,
		HIRELING_ABSOLUTE,
		HIRELING_ABSOLUTE_PERCENT,
		LINEBREAKS_TO_SPACE
	}
}
