using System;

namespace Legacy.Core.NpcInteraction
{
	public enum ETargetCondition
	{
		NONE,
		REPAIR,
		CURE,
		IDENTIFY,
		RESURRECT,
		RESTORATION,
		CAST,
		REST,
		HIRE,
		HIRE_CLAIRVOYANCE,
		HIRE_ENHCLAIRVOYANCE,
		HIRE_SPOTSECRETS,
		HIRE_ENHSPOTSECRETS,
		HIRE_DANGERSENSE,
		HIRE_IDENTIFY,
		HIRE_CURE,
		HIRE_REPAIR,
		HIRE_REST,
		HIRE_RESTWELL,
		HIRE_TRADEPOTS,
		HIRE_TRADEBUY,
		HIRE_BONUSMF,
		HIRE_BONUSGF,
		HIRE_BONUSXP,
		HIRE_BONUSTRAPCHANCE,
		HIRE_BONUSSECRETCHANCE,
		HIRE_BONUSTRADEDISC,
		HIRE_MULE,
		HIRE_AGGROREDUCE,
		HIRE_REVEALBEASTIARY,
		HIRE_MMEXPLODISTANCE,
		HIRE_REVIVE,
		HIRE_RESTORE,
		HIRE_BLOCK,
		HIRE_DEFBUFF,
		FIRE,
		HIRE_AND_CHANGE_MAP,
		FIRE_AND_GIVE_QUEST
	}
}
