using System;

namespace Legacy.Core.Achievements
{
	[Flags]
	public enum ETriggerType
	{
		NONE = 0,
		QUEST_STEP_COMPLETED = 1,
		ITEM_EQUIPPED = 2,
		CHARACTER_LEVEL_UP = 3,
		PARTY_GOLD_CHANGED = 4,
		NEW_DAY = 5,
		UNLOCKED_ADVANCED_CLASS = 6,
		LEARNED_SPELL = 7,
		INTERACT_WITH_OBJECT = 8,
		ITEM_ADDED_TO_INVENTORY = 9,
		PARTY_POSITION_CHANGED = 10,
		CHARACTER_REVIVED = 11,
		MONSTER_ATTACKED_CHARACTER = 12,
		MONSTER_DIED = 13,
		CASTED_SPELL = 14,
		CHARACTER_DIED = 15,
		UNCOVERED_TILE = 16,
		RESTED = 17
	}
}
