using System;

namespace Legacy.Core.Spells.MonsterSpells
{
	public enum EMonsterSpell
	{
		NONE,
		FIREBALL,
		FIREBOLT,
		BATTLE_SPIRIT,
		ICE_SHARDS,
		DEEP_FREEZE,
		LIQUID_MEMBRANE,
		ICE_STORM,
		CHAIN_LIGHTNING,
		LIGHTNING_BOLT,
		PETRIFACTION,
		POISON_SPIT,
		REGROWTH,
		STONE_SKIN,
		GLARING_LIGHT,
		PURIFY,
		CONFUSION,
		AGONIZING_PURGE,
		TORPOR,
		OVERWHELMING_ASSAULT,
		DARK_NOVA,
		DARK_RESTORATION,
		WITHERING_BREATH,
		CRYSTAL_SHARDS,
		CRYSTAL_SHELL,
		CRYSTAL_CAGE,
		EXPLOSIVE_CRYSTAL_CAGE,
		BLINK,
		BACKSTAB,
		SWOOP,
		SHADOW_BOLT,
		CRUSH,
		CELESTIAL_ARMOUR,
		HOUR_OF_JUSTICE,
		SUN_RAY,
		MASS_HEAL,
		FLICKERING_LIGHT,
		FLICKER,
		PACIFICATION
	}
}
